name: "check-flake"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "flake.nix"
      - "flake.lock"
      - "secrets.nix"
      - "publicKeys/**"
  workflow_dispatch:

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check formatting
        run: nix fmt -- -c .
  check-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check flake evaluation
        run: nix flake check --all-systems
      - name: Check secrets evaluation
        run: nix eval --file ./secrets.nix
